Wording changes in openEQUELLA section
openequella/openequella.github.io pull request #18
Opened 2018-11-01 03:59 UTC by goetzk

Removed the placeholders which don't seem useful any longer and updated some
other wording in the install steps.

2018-11-01 14:53 UTC, cbeach47 requested changes
Good catch - the way to find a release was a WIP during open sourcing of oEQ, and this page was a loose end.

I mentioned a couple of changes I'd suggest.

2018-11-01 14:53 UTC, cbeach47 commented on guides/InstallationAdminGuide.md
> +1. Download equella-installer-x.x.zip (substitute x for the current minor version) from https://github.com/equella/Equella/releases
I would change it to:

Obtain an openEQUELLA installer.  You can either download a demo installer from https://github.com/equella/Equella/releases or build a production installer via `sbt`.  Demo installers do not contain Kaltura integration or Oracle DB drivers, and use a self-signed Java signing certificate.  The file format is equella-installer-x.y.zip (substitute x for the current major version, and y for the current minor version)

2018-11-01 14:53 UTC, cbeach47 commented on guides/InstallationAdminGuide.md
> +2. Extract the equella-installer-x.x.zip file to a temporary directory.
Change to:
Extract the equella-installer-x.y.zip file to a temporary directory.

2018-11-01 14:53 UTC, cbeach47 commented on guides/InstallationAdminGuide.md
> +Note: It may be possible to install without requiring a GUI; see https://groups.google.com/a/apereo.org/d/msg/equella-users/v-MMOuoa7mk/UDbmSkKRAwAJ for discussion if this is important to you.
We can use stronger language, such as:

Note: It is possible to install without requiring a GUI.  While not widespread as a production installation method, it's consistently used in the docker logic. see ....

2018-11-13 04:30 UTC, goetzk commented
Hi @cbeach47 ,
I've brought those suggestions in verbatim in the latest commit.

2018-12-22 14:18 UTC, cbeach47 approved these changes

2018-12-22 14:18 UTC, merged